[versions]
firebaseBom = "34.3.0"
j2objcAnnotations = "2.8"
agp = "8.13.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activityCompose = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-constraintlayout = "2.2.1"
androidx-material = "1.13.0"
compose-plugin = "1.8.2"
kotlin = "2.2.0"
kotlinVersion = "2.2.0"
kotlinxCoroutinesCore = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
androidxJunit = "1.3.0"
espressoCore = "3.7.0"
composeUiTest = "1.9.2"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.9.0"
lifecycleLivedataKtx = "2.9.4"
lifecycleViewmodelKtx = "2.9.4"
mockkAndroid = "1.14.5"
mockkCommon = "1.12.5"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
material3Android = "1.4.0"
uiTextGoogleFonts = "1.9.2"
workRuntimeKtx = "2.10.5" # 2.10.0 requires Android sdk 35
places = "4.4.1"
uiGraphicsAndroid = "1.9.2"
annotationJvm = "1.9.1"
dataStorePreferences = "1.1.7"
kotlinxAtomic = "0.29.0"
koin = "4.1.0"
maplibreAndroid = "11.13.0" # 11.2.0 is SEGV_MAPERR
maplibreAndroidAnnotation = "3.0.2"
playServicesLocation = "21.3.0"
napier = "2.7.1"
featureDeliveryKtx = "2.1.0"
coreSplashscreen = "1.0.1"
icerockMoko = "0.25.0"
ktlint = "1.4.1"
detekt = "1.23.7"

[libraries]
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
j2objc-annotations = { group = "com.google.j2objc", name = "j2objc-annotations", version.ref = "j2objcAnnotations" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotationJvm" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStorePreferences" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-plugin" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mockk-android-v1120 = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
mockk-common-v1120 = { module = "io.mockk:mockk-common", version.ref = "mockkCommon" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "dataStorePreferences" }
kotlinx-atomic = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "kotlinxAtomic" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeUiTest" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeUiTest" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidCompose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
maplibre-android = { group = "org.maplibre.gl", name = "android-sdk", version.ref = "maplibreAndroid" }
maplibre-android-annotation = { group = "org.maplibre.gl", name = "android-plugin-annotation-v9", version.ref = "maplibreAndroidAnnotation" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }
feature-delivery-ktx = { group = "com.google.android.play", name = "feature-delivery-ktx", version.ref = "featureDeliveryKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
icerock-moko-resources = { group = "dev.icerock.moko", name= "resources", version.ref = "icerockMoko" }
icerock-moko-resources-compose = { group = "dev.icerock.moko", name= "resources-compose", version.ref = "icerockMoko" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
licenseReport = { id = "com.github.jk1.dependency-license-report", version = "2.9" }
icerock-moko-multiplatform = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "icerockMoko" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
