name: Build Apps

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_android:
    name: Build Android app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build app
        run: ./gradlew assemble --stacktrace

  build_ios:
    name: Build iOS app
    runs-on: macos-14
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Validate Gradle Wrapper
       uses: gradle/actions/wrapper-validation@v3

     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         distribution: 'zulu'
         java-version: 17

     - name: Select Xcode 16
       uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: '16.0'

     - name: Build app (iOS Simulator 18.0)
       run: |
         xcodebuild            -project iosApp/iosApp.xcodeproj            -scheme iosApp            -configuration Debug            -sdk iphonesimulator            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0'            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO | xcpretty
       env:
         NSUnbufferedIO: YES

  test_shared_module: # New job for shared module tests
    name: Test Shared KMP Module
    runs-on: ubuntu-latest # Or macos-latest if you have macOS specific tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests for shared module (all targets)
        run: ./gradlew :shared:cleanTestDebugUnitTest :shared:testDebugUnitTest --tests "com.worldwidewaves.shared.*" --stacktrace

      - name: Upload Test Results
        if: always() # Always run this step to upload results even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: shared-module-test-results
          path: shared/build/test-results/
          retention-days: 7